name             'packer-payload'
maintainer       'Chris Marchesi'
maintainer_email 'chrism@vancluevertech.com'
license          'MIT'
description      'Payload for Packer Chef provisioner'
long_description 'Payload for Packer Chef provisioner'
version          '1.0.0'

depends 'apt'
depends 'java'
depends 'buid-essential'
depends 'poise-ruby'
depends 'poise-python'
